// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfQuehq6BRTKqUr_kdNhRe3aLESvVkvVg',
    appId: '1:650428267401:web:b323f687d5dd4102727f58',
    messagingSenderId: '650428267401',
    projectId: 'aura-safe-app',
    authDomain: 'aura-safe-app.firebaseapp.com',
    storageBucket: 'aura-safe-app.firebasestorage.app',
    measurementId: 'G-NJNE2PSB57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHWBzYQQhxhPDl9lQ5b0IKZPzuCXtvEsg',
    appId: '1:650428267401:android:47d1061cb6ff9aae727f58',
    messagingSenderId: '650428267401',
    projectId: 'aura-safe-app',
    storageBucket: 'aura-safe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUI15eaOvHSIAxgydDlv9ex9vkRVVCXY8',
    appId: '1:650428267401:ios:9d746f1b51e474d2727f58',
    messagingSenderId: '650428267401',
    projectId: 'aura-safe-app',
    storageBucket: 'aura-safe-app.firebasestorage.app',
    iosBundleId: 'com.example.auraSafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUI15eaOvHSIAxgydDlv9ex9vkRVVCXY8',
    appId: '1:650428267401:ios:9d746f1b51e474d2727f58',
    messagingSenderId: '650428267401',
    projectId: 'aura-safe-app',
    storageBucket: 'aura-safe-app.firebasestorage.app',
    iosBundleId: 'com.example.auraSafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfQuehq6BRTKqUr_kdNhRe3aLESvVkvVg',
    appId: '1:650428267401:web:b6fe92396a6d9635727f58',
    messagingSenderId: '650428267401',
    projectId: 'aura-safe-app',
    authDomain: 'aura-safe-app.firebaseapp.com',
    storageBucket: 'aura-safe-app.firebasestorage.app',
    measurementId: 'G-EGD6GCF9YL',
  );
}
